### ISSUE TITLE
Invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by antoineandrieu** [lxe/tts-server#3]
**Description:**
When sending a POST request to /tts, the server returns an error related to tensor operations in PyTorch.

**Request:**
```bash
curl -X POST -H "Content-Type: application/json" -H "Accept: audio/wav" -d '{
  "sessionId": 12345,
  "text": "Embrace the chaos and let your words dance to the rhythm of imagination!",
  "alpha": 0.2,
  "beta": 0.4,
  "diffusion_steps": 10,
  "embedding_scale": 1.5
}' "http://localhost:7000/tts"
```

**Response**
```bash
{"error":"invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number"}
```

**Comment by nomq1** [comment]
I had that too, worked perfectly on a docker container.

**Comment by antoineandrieu** [comment]
On my side, it works on the host but not inside a container. Both Ubuntu 22.04 - Python 3.10. Weird!

**Comment by antoineandrieu** [comment]
The problem was espeak missing in the container, should have read the readme!
